### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by pakeke-constructor** [IAmCheeseman/love-rich-text#7]
API idea:
```lua
local t = { foo = "hi" }
RichText.new(font, "foo is {$foo}", t)
-- 'foo is hi'
```

Dynamic value support:
```lua
local t = {}
t.foo = function()
  return "123"
end

text = RichText.new(font, "foo is {$foo}", t)
-- 'foo is 123'
```

**Comment by IAmCheeseman** [comment]
This is less rich text and more string formatting. Rich text is for visual effects, while string formatting is for making strings. Just use `RichText.new(font, ("foo is %s"):format(t.foo()))`.

**Comment by pakeke-constructor** [comment]
True true!

**Comment by pakeke-constructor** [comment]
I guess the downside of formatting the string outside of `RichText` is that we will have to re-construct the string every time a value changes.
For example:
```lua
RichText.new(("Current health is %d"):format(ent.health))
```
^^^ Must re-construct the string every time health changes
